### ISSUE TITLE
RuntimeError: Missing format!

### ISSUE THREAD

**Issue by RajithaKrishnan** [scls19fr/pandas_confusion#7]
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pandas-confusion

**Comment by scls19fr** [comment]
Full traceback will help

Why are you doing this ?


 why not just 

    pip install pandas_confusion

or

    git clone https://github.com/scls19fr/pandas_confusion.git
    cd pandas_confusion
    python setup.py install

or

    sudo pip install git+git://github.com/scls19fr/pandas_confusion.git

**Comment by scls19fr** [comment]
Any news ?

**Comment by VanZeidt** [comment]
Either pip, easy_install and python setup.py install give the same error:

G:\Windows_Downloads\pandas_confusion-0.0.4>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 112, in <module>
    'sample=sample:main',
  File "C:\Python27\lib\distutils\core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "build\bdist.win-amd64\egg\setuptools\dist.py", line 266, in __init__
  File "C:\Python27\lib\distutils\dist.py", line 287, in __init__
    self.finalize_options()
  File "build\bdist.win-amd64\egg\setuptools\dist.py", line 301, in finalize_options
  File "g:\windows_downloads\pandas_confusion-0.0.4\setuptools_markdown-0.2-py2.7.egg\setuptools_markdown.py", line 22, in long_description_markdown_filename
    output = pypandoc.convert(markdown_filename, 'rst')
  File "C:\Python27\lib\site-packages\pypandoc-1.1.2-py2.7.egg\pypandoc\__init__.py", line 50, in convert
    outputfile=outputfile, filters=filters)
  File "C:\Python27\lib\site-packages\pypandoc-1.1.2-py2.7.egg\pypandoc\__init__.py", line 68, in _convert
    raise RuntimeError('Missing format!')
RuntimeError: Missing format!

**Comment by scls19fr** [comment]
Hum... that's strange I think the issue is with pypandoc not with pandas_confusion.

but I think I should convert `README.md` to `README.rst` by hand (or using `pandoc --from=markdown --to=rst --output=README.rst README.md`) and use directly `README.rst` file in setup.py

**Comment by scls19fr** [comment]
@RajithaKrishnan @VanZeidt

I have fix `setup.py` and upload to PyPi. it should be working now.

Could you confirm or invalidate ?

**Comment by VanZeidt** [comment]
Now it works like charm, thanks a lot for your fast answer!

**Comment by scls19fr** [comment]
My pleasure. Feel free to be in touch with me on LinkedIn https://www.linkedin.com/in/sebastiencelles
